# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  gripper_prismatic_joint_1:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_prismatic_joint_2:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_revolute_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  joint_1:
    has_velocity_limits: true
    max_velocity: 0.785
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0